/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las.views;

import SeverConnector.Connector;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import las.common_classes.PatternChecker;
import las.controller.GramaNiladariDivisionController;
import las.models.GramaNiladariDivision;

/**
 *
 * @author Uer
 */
public class GramaNiladhariForm extends javax.swing.JInternalFrame {
    GramaNiladariDivisionController GramaNiladariDivisionController;
    /**
     * Creates new form GramaNiladhariForm
     */
    public GramaNiladhariForm() {

        initComponents();
        
          try {
            Connector sConnector = Connector.getSConnector();
            GramaNiladariDivisionController=sConnector.getGramaNiladariDivisionController();
        } catch (RemoteException | SQLException | NotBoundException | MalformedURLException|ClassNotFoundException ex) {
            Logger.getLogger(ApplicantForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        gnnamenotvalidlabel.setVisible(false);
        gnd_update_combo.requestFocus();
        gnd_search_combo.setMaximumRowCount(10);
        gnd_search_combo.setEditable(true);
        JTextComponent editor = (JTextComponent) gnd_search_combo.getEditor().getEditorComponent();

        editor.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {

                gnd_search_combo.setPopupVisible(true);
                String test = String.valueOf(gnd_search_combo.getEditor().getItem());
                gnd_search_combo.removeAllItems();
                try {
                    ArrayList<GramaNiladariDivision> simmilarGndDivisionNumbers = GramaNiladariDivisionController.getSimmilarGndDivisionNumbers(test);
                    for (GramaNiladariDivision simmilarGndDivisionNumber : simmilarGndDivisionNumbers) {
                        gnd_search_combo.addItem(simmilarGndDivisionNumber.getDivisionNumber());
                    }
                    gnd_search_combo.getEditor().setItem(test);
                } catch (ClassNotFoundException | SQLException|RemoteException ex) {
                    Logger.getLogger(GramaNiladhariForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        });
        try {
            ArrayList<GramaNiladariDivision> allGNDDetail = GramaNiladariDivisionController.getAllGNDDetail();
            for (GramaNiladariDivision gndDetail : allGNDDetail) {
                gnd_update_combo.addItem(gndDetail.getDivisionNumber());
            }
        } catch (ClassNotFoundException | SQLException | RemoteException ex) {
            Logger.getLogger(GramaNiladhariForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allGNDDetailTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        gnd_load_buttun = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        gndnolabel = new javax.swing.JLabel();
        gndnamelabel = new javax.swing.JLabel();
        gnd_update_combo = new javax.swing.JComboBox();
        zonelabel = new javax.swing.JLabel();
        gnnamelabel = new javax.swing.JLabel();
        gnd_name_test = new javax.swing.JTextField();
        gnd_zone_test = new javax.swing.JTextField();
        gnd_gramaniladari_name = new javax.swing.JTextField();
        gnd_update_button = new javax.swing.JButton();
        gnd_cancel_button = new javax.swing.JButton();
        gnnamenotvalidlabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        gnd_search_combo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gnd_searchName_test = new javax.swing.JTextField();
        gnd_searchZone_test = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gnd_searchGramaniladari_name = new javax.swing.JTextField();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(868, 518));

        allGNDDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zone", "GND Name", "GND No", "Grama Niladhari"
            }
        ));
        jScrollPane1.setViewportView(allGNDDetailTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        gnd_load_buttun.setText("Load");
        gnd_load_buttun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_load_buttunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gnd_load_buttun, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(gnd_load_buttun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View All GNDs", jPanel2);

        gndnolabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gndnolabel.setText("Grama Niladhari Division No");

        gndnamelabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gndnamelabel.setText("Grama Niladhari Division Name");

        gnd_update_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gnd_update_comboItemStateChanged(evt);
            }
        });
        gnd_update_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_update_comboActionPerformed(evt);
            }
        });
        gnd_update_combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_update_comboKeyReleased(evt);
            }
        });

        zonelabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        zonelabel.setText("Zone");

        gnnamelabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gnnamelabel.setText("Grama Niladhari Name");

        gnd_name_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_name_testActionPerformed(evt);
            }
        });
        gnd_name_test.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_name_testKeyReleased(evt);
            }
        });

        gnd_zone_test.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_zone_testKeyReleased(evt);
            }
        });

        gnd_gramaniladari_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_gramaniladari_nameActionPerformed(evt);
            }
        });
        gnd_gramaniladari_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_gramaniladari_nameKeyReleased(evt);
            }
        });

        gnd_update_button.setText("Update");
        gnd_update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_update_buttonActionPerformed(evt);
            }
        });
        gnd_update_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_update_buttonKeyReleased(evt);
            }
        });

        gnd_cancel_button.setText("Cancel");
        gnd_cancel_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_cancel_buttonKeyReleased(evt);
            }
        });

        gnnamenotvalidlabel.setBackground(new java.awt.Color(204, 0, 0));
        gnnamenotvalidlabel.setForeground(new java.awt.Color(204, 0, 0));
        gnnamenotvalidlabel.setText("Not Valid");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gndnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gndnamelabel)
                            .addComponent(zonelabel)
                            .addComponent(gnnamelabel))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(gnd_zone_test, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(gnd_update_combo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gnd_name_test, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gnd_gramaniladari_name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gnnamenotvalidlabel)
                        .addGap(0, 387, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gnd_update_button)
                        .addGap(42, 42, 42)
                        .addComponent(gnd_cancel_button)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gndnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gnd_update_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gndnamelabel)
                    .addComponent(gnd_name_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zonelabel)
                    .addComponent(gnd_zone_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gnnamelabel)
                    .addComponent(gnd_gramaniladari_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gnnamenotvalidlabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gnd_update_button)
                    .addComponent(gnd_cancel_button))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update GND Details", jPanel4);

        gnd_search_combo.setAutoscrolls(true);
        gnd_search_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gnd_search_comboItemStateChanged(evt);
            }
        });
        gnd_search_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_search_comboActionPerformed(evt);
            }
        });
        gnd_search_combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gnd_search_comboKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gnd_search_comboKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Grama Niladhari Division No");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Grama Niladhari Division Name");

        gnd_searchName_test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_searchName_testActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Zone");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Grama Niladhari Name");

        gnd_searchGramaniladari_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnd_searchGramaniladari_nameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(gnd_search_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addGap(32, 32, 32)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gnd_searchZone_test)
                        .addComponent(gnd_searchName_test)
                        .addComponent(gnd_searchGramaniladari_name))
                    .addContainerGap()))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gnd_search_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(gnd_searchName_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(gnd_searchZone_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(gnd_searchGramaniladari_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(87, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search GND", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gnd_gramaniladari_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_gramaniladari_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnd_gramaniladari_nameActionPerformed

    private void gnd_load_buttunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_load_buttunActionPerformed
        DefaultTableModel model = (DefaultTableModel) allGNDDetailTable.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
        try {
            ArrayList<GramaNiladariDivision> allGNDDetail = GramaNiladariDivisionController.getAllGNDDetail();

            for (GramaNiladariDivision GNDDetail : allGNDDetail) {
                Object[] rowdata = {GNDDetail.getZoneName(), GNDDetail.getDivisionName(), GNDDetail.getDivisionNumber(), GNDDetail.getGramaNilardariName()};
                model.addRow(rowdata);
            }
        } catch (ClassNotFoundException | SQLException |RemoteException ex) {
            Logger.getLogger(GramaNiladhariForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_gnd_load_buttunActionPerformed

    private void gnd_update_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_update_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnd_update_comboActionPerformed

    private void gnd_update_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gnd_update_comboItemStateChanged
        try {
            GramaNiladariDivision searchGND = GramaNiladariDivisionController.searchGND((String) gnd_update_combo.getSelectedItem());
            gnd_name_test.setText(searchGND.getDivisionName());
            gnd_zone_test.setText(searchGND.getZoneName());
            gnd_gramaniladari_name.setText(searchGND.getGramaNilardariName());
        } catch (ClassNotFoundException | SQLException | RemoteException ex) {
            Logger.getLogger(GramaNiladhariForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gnd_update_comboItemStateChanged

    private void gnd_update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_update_buttonActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Do yo want to update");
        if (showConfirmDialog == 0) {
            GramaNiladariDivision gramaNiladariDivision = new GramaNiladariDivision((String) gnd_update_combo.getSelectedItem(), gnd_name_test.getText(), gnd_zone_test.getText(), gnd_gramaniladari_name.getText());
            try {
                boolean updateGND = GramaNiladariDivisionController.updateGND(gramaNiladariDivision);
                if (updateGND) {
                    JOptionPane.showMessageDialog(rootPane, "updated succesfully");
                    gnd_name_test.setText(null);
                    gnd_zone_test.setText(null);
                    gnd_gramaniladari_name.setText(null);
                    gnd_update_combo.setSelectedItem(null);
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "updated is not success");
                }

            } catch (ClassNotFoundException | SQLException | RemoteException ex) {
                Logger.getLogger(GramaNiladhariForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_gnd_update_buttonActionPerformed

    private void gnd_name_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_name_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnd_name_testActionPerformed

    private void gnd_search_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gnd_search_comboItemStateChanged
        try {
            GramaNiladariDivision searchGND = GramaNiladariDivisionController.searchGND((String) gnd_search_combo.getSelectedItem());
            if (searchGND != null) {
                gnd_searchName_test.setText(searchGND.getDivisionName());
                gnd_searchZone_test.setText(searchGND.getZoneName());
                gnd_searchGramaniladari_name.setText(searchGND.getGramaNilardariName());
            }
        } catch (ClassNotFoundException | SQLException | RemoteException ex) {
            Logger.getLogger(GramaNiladhariForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_gnd_search_comboItemStateChanged

    private void gnd_search_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_search_comboActionPerformed

    }//GEN-LAST:event_gnd_search_comboActionPerformed

    private void gnd_searchName_testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_searchName_testActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnd_searchName_testActionPerformed

    private void gnd_searchGramaniladari_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnd_searchGramaniladari_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnd_searchGramaniladari_nameActionPerformed

    private void gnd_search_comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_search_comboKeyPressed
        //ComboBoxModel model = gnd_search_combo.getModel();

    }//GEN-LAST:event_gnd_search_comboKeyPressed

    private void gnd_search_comboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_search_comboKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gnd_search_comboKeyReleased

    private void gnd_update_comboKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_update_comboKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            gnd_name_test.requestFocus();
        }
    }//GEN-LAST:event_gnd_update_comboKeyReleased

    private void gnd_name_testKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_name_testKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            gnd_zone_test.requestFocus();
        }
        else if(evt.getKeyCode()==KeyEvent.VK_UP){
            gnd_update_combo.requestFocus();}
        
    }//GEN-LAST:event_gnd_name_testKeyReleased

    private void gnd_zone_testKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_zone_testKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            gnd_gramaniladari_name.requestFocus();
        }
        else if(evt.getKeyCode()==KeyEvent.VK_UP){
            gnd_name_test.requestFocus();}
    }//GEN-LAST:event_gnd_zone_testKeyReleased

    private void gnd_gramaniladari_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_gramaniladari_nameKeyReleased
        // TODO add your handling code here:
        gnnamenotvalidlabel.setVisible(false);
        String newtext=PatternChecker.checkstring(gnd_gramaniladari_name.getText());
        gnd_gramaniladari_name.setText(newtext);
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(PatternChecker.checkStringdirect(gnd_gramaniladari_name.getText())){
                gnd_update_button.requestFocus();
            }
            else{
                gnnamenotvalidlabel.setVisible(true);
            }
           
        }
        else if(evt.getKeyCode()==KeyEvent.VK_UP){
            gnd_zone_test.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN){
            gnd_update_button.requestFocus();}
    }//GEN-LAST:event_gnd_gramaniladari_nameKeyReleased

    private void gnd_update_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_update_buttonKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            gnd_gramaniladari_name.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_RIGHT){
            gnd_cancel_button.requestFocus();}
    }//GEN-LAST:event_gnd_update_buttonKeyReleased

    private void gnd_cancel_buttonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gnd_cancel_buttonKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            gnd_gramaniladari_name.requestFocus();}
        else if(evt.getKeyCode()==KeyEvent.VK_LEFT){
            gnd_update_button.requestFocus();}
    }//GEN-LAST:event_gnd_cancel_buttonKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allGNDDetailTable;
    private javax.swing.JButton gnd_cancel_button;
    private javax.swing.JTextField gnd_gramaniladari_name;
    private javax.swing.JButton gnd_load_buttun;
    private javax.swing.JTextField gnd_name_test;
    private javax.swing.JTextField gnd_searchGramaniladari_name;
    private javax.swing.JTextField gnd_searchName_test;
    private javax.swing.JTextField gnd_searchZone_test;
    private javax.swing.JComboBox gnd_search_combo;
    private javax.swing.JButton gnd_update_button;
    private javax.swing.JComboBox gnd_update_combo;
    private javax.swing.JTextField gnd_zone_test;
    private javax.swing.JLabel gndnamelabel;
    private javax.swing.JLabel gndnolabel;
    private javax.swing.JLabel gnnamelabel;
    private javax.swing.JLabel gnnamenotvalidlabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel zonelabel;
    // End of variables declaration//GEN-END:variables
}
